version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gatcha-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/gatcha

volumes:
  mongo-data: